import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/landingpage.module.css'
import {useRouter} from "next/router"
export default function LandingPage() {
  const router = useRouter()
  return (
    <div className={styles.container}>
      <Head>
        <title>Mercearia da Bianca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
        <div className={styles.fundoImagem} >
          <div className={styles.textoTudo}>
            <div className={styles.frase}>
              Bem-vindo à nossa Loja !
            </div>
            <div className={styles.frase2}>
              Fique a par de todas as nossas novidades !
            </div>
            <button onClick={() => router.push("/homepage")} className={styles.butt}>
              Venha conhecer
            </button>
          </div>
        </div>
  
    </div>
  )
}
