import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function LandingPage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mercearia da Bianca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       {/* <div className={styles.imgDiv}/>
        <div className={styles.fundo}>
        
            <div className={styles.frase}>
              Bem-Vindo a nossa Loja !
            </div>
            <div className={styles.frase2}>
              qualquer coisa !
            </div>
              <button className={styles.butt}>
                Venha conheçer
              </button>
          
          

        </div> */}
        <div className={styles.fundoImagem} >
          <div className={styles.textoTudo}>
            <div className={styles.frase}>
              Bem-vindo à nossa Loja !
            </div>
            <div className={styles.frase2}>
              Fique a par de todas as nossas novidades !
            </div>
            <button className={styles.butt}>
              Venha conhecer
            </button>
          </div>
        </div>
  
    </div>
  )
}
