import Head from 'next/head'
import Image from 'next/image'
import styles from '../../../styles/awards.module.css'
import { useRouter } from "next/router"
import { useState } from 'react'


export default function award() {

  const router = useRouter()

  return (

    <div className={styles.divGrande}>
      <Head>
        <title>Mercearia da Bianca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mini.png" />
      </Head>

      <div className={styles.logoVoltar}>
        <div className={styles.logoCarro}><img width="280px" height="90px" src="../logoOficial.png" /></div>
        <div className={styles.voltar} onClick={() => router.push("/homepage")}>X</div>
      </div>
      <hr className={styles.hr}></hr>

      <div className={styles.titulos}>Parabéns, acertaste !</div>
      <div>
        <Image
          src="/Cupcake.webp"
          alt="Imagem1"
          height={300}
          width={250} />
      </div>
      <div className={styles.bordacodigo}>
        <img width="160px" height="60px" src="../barras.png" />
      </div>
      <div className={styles.desc}>Para redimir esta oferta, apresenta o seguinte código na caixa.</div>

    </div>


  )
}