import Head from 'next/head'
import Image from 'next/image'
import styles from '../../../styles/awards.module.css'
import { useRouter } from "next/router"
import { useState } from 'react'


export default function award() {
  

  
  return (
    
    <div className={styles.divGrande}>
      <Head>
        <title>Mercearia da Bianca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.logoCarro}><img  width="40px" height="40px" src="../carrinhologo.png" /></div>
      <div className={styles.logoTipo}>
        
      MERCEARIA DA BIANCA
      </div>
      <hr className={styles.hr}></hr>
        <div className={styles.titulos}>Parabéns, acertaste !</div>
        <div>
        <Image
                  src="/Cupcake.webp"
                  alt="Imagem1"
                  height={300}
                  width={250} />
        </div>
        <div className={styles.desc}>Para redimir esta oferta, apresenta o seguinte código na caixa.</div>
        <div></div>
    </div>


  )
}