import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/prize.module.css'
import { useRouter } from "next/router"
import { useState, useEffect } from 'react'
export default function Prize() {
    const router = useRouter()
    const [answers, setAnswers] = useState([])


    useEffect(() => {
        async function CallBack() {
            const res = await fetch(
                `../api/answersApi?minute=${new Date().getMinutes()
                }`, {
                method: "GET"
            })
            console.log("FRONTEND", res)
            const json = await res.json()
            setAnswers(json.a)
            console.log("Fim do UseEffect")
        }
        CallBack()
    }, [])

    async function checkAnswer(e) {
        const res = await fetch(
            `../api/checkAnswer?answer=${e}`,
            {
                method: "GET"
            })
        console.log("FRONTEND", res)
        const json = await res.json()
        console.log("TESTE", json.a)
        console.log("Fim do UseEffect")
        if(json.a) {
            router.push("/award")
        }

        // e == json.a ? 
    }



    return (
        <div>
            <Head>
                <title>Mercearia da Bianca</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <div className='styles.pergunta'>
                    AQUI VAI FICAR A PERGUNTA
                </div>


                {answers.map(e => (<div onClick={() => checkAnswer(e)} className='styles.respostas' key={e} > {e} </div>))}


            </div>

        </div>
    )
}
