import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/homepage.module.css'
import {useRouter} from "next/router"
export default function HomePage() {
  const router = useRouter()
  return (
    <div className={styles.geral}>
      <Head>
        <title>Mercearia da Bianca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.escrita}>
            <div className={styles.tempoEspera}>
            <p>Tempo de espera:</p>
            <p>8 Minutos</p>
            </div>
            <div className={styles.pessoas}>
            <p>Fila de espera:</p>
            <p>4 Pessoas</p>
            </div>
          </div>
      <div className={styles.metadeBaixo} >
      <div className={styles.catalgo}>
            <p>CATÁLOGO</p>
            </div>
            <div className={styles.jogo}>
            <p>JOGO</p>
            </div>
        </div>
  
    </div>
  )
}
