import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/homepage.module.css'
import { useRouter } from "next/router"
export default function HomePage() {
  const router = useRouter()
  return (
    <div className={styles.geral}>
      <Head>
        <title>Mercearia da Bianca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.logoCarro}><img  width="280px" height="90px" src="../logoOficial.png" /></div>
      <hr className={styles.hr}></hr>
  
      <div className={styles.baixo}>
        <div className={styles.catalgo } onClick={() => router.push("/brochure")}>
          <p className={styles.textoCatalogo}>CATÁLOGO</p>
        </div>
        <div className={styles.jogo} onClick={() => router.push("/prizes")}>
          <p className={styles.textoPremios}>GANHE HOJE PRÉMIOS</p>
        </div>
      </div>
      <div className={styles.cima}>
        <div className={styles.tempoEspera}>
          <span>Tempo de espera</span>
          <p className={styles.tempoMin}>8 Minutos</p>
        </div>
        <div className={styles.pessoas}>
          <span>Fila de espera</span>
          <p className={styles.quantPessoas}>4 Pessoas</p>
        </div>
      </div>

    </div>


  )
}
